#ifndef RELEASEVERSION_H
#define RELEASEVERSION_H

#define MAJOR_VERSION 2
#define MINOR_VERSION 5
#define PATCH_VERSION 0

#define VVV_STRINGIFY(x) #x
#define VVV_TOSTRING(x) VVV_STRINGIFY(x)

#if PATCH_VERSION == 0
#define RELEASE_VERSION "v" VVV_TOSTRING(MAJOR_VERSION) "." VVV_TOSTRING(MINOR_VERSION)
#else
#define RELEASE_VERSION "v" VVV_TOSTRING(MAJOR_VERSION) "." VVV_TOSTRING(MINOR_VERSION) "." VVV_TOSTRING(PATCH_VERSION)
#endif

#endif /* RELEASEVERSION_H */
